export const questions = [
  "Have you ever won a judged award?",
  "Have you ever broken a brain?",
  "Have you ever lost a whole ass C-Channel >30 holes?",
  "Have you ever looked for build tutorials?",
  "Have you ever owned a field?",
  "Have you ever lost to AI notebook?",
  "Have you ever been screwed over by a referee?",
  "Have you ever slept with your robot?",
  "Have you ever holecounted ruigoon?",
  "Have you ever gooned to lukedoesrobotics????",
  "Are you an asian male with glasses?",
  "Has your auton hit more than twice in a tournament?",
  "Have you ever screwed in a nylock backwards?",
  "Have you ever coded autons after midnight?",
  "Have you ever coded autons at the competition?",
  "Do you have a team sticker?",
  "Have you ever used a zip tie as a substitute for a screw?",
  "Have you ever disconnected during a match?",
  "Have you ever disconnected during a skills run?",
  "Have you ever filmed a robot reveal?",
  "Do you do team gooning sessions?",
  "Have you ever been in some dude's basement?",
  "Is your coder a femboy?",
  "Are you part of a team that isn't school owned?",
  "Have you spent more than $1000 on VEX?",
  "Do you spend >30% of your build sessions playing clash royale?",
  "Do you have a j*b?",
  "Are you present on l*nkedin?",
  "Have you ever dropped a screwdriver on a laptop?",
  "Have you ever flown somewhere for a VEX Competition?",
  "Do you run odihmetry?",
  "Have you ever built your drivetrain backwards?",
  "Do you run full omni?",
  "Does your robot run 600 rpm direct?",
  "Do you have a non-tank drivetrain?",
  "Do you have two drivers?",
  "Is 9motorgang your goat?",
  "Do you buy parts from robosource?",
  "Have you ever heard of 210T?",
];
